spring:
  datasource:
    url: jdbc:mysql://localhost:3306/l2store
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create

    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        # format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: <YOUR_EMAIL>
    password: <YOUR_PASSWORD>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

paypal:
  mode: sandbox
  client:
    id: <PAYPAL_ID>
    secret: <PAYPAL_SECRET>
